### ISSUE TITLE
y-coordinate issue

### ISSUE THREAD

**Issue by btupper** [BigelowLab/cefi#1]
@SeascapeScience See this [page](https://github.com/BigelowLab/cefi/blob/main/stars-issues.md) for gory details but in a nutshell...

The data is weird at it's northern limits - see how the Gulf of St Lawrence is trying to emigrate to the US?

![image](https://github.com/user-attachments/assets/694ddbee-7834-4e14-acf9-e8603e3216bc)

The y-coordinates have a fold.  Here's a simple plot of the y-corrdinates...

![image](https://github.com/user-attachments/assets/cc8a9e0a-2c8e-4898-8b75-7e4756f3acad)

I have written to CEFI data-web help and they can see the same issue, but have not offered a solution yet.  Do I pause CEFI-work for now?  Or proceed assuming that they can help me resolve the issue later and that we are ok below 47N anyway?

**Comment by SeascapeScience** [comment]
Woah, I think we need to pause until you hear back from them. There could be other more subtle discrepancies further south.

**Comment by chiaweh2** [comment]
@btupper thanks for submitting the question through the psl.data email. We are trying to setup a new email just for CEFI portal and data. Stay tuned! But I think we can also interact through GitHub. I will put the email I response to you here as a record so if other people have the same problem I can refer to this issue. 

> The data you are trying to access is the raw grid data. On the CEFI portal, we have a [cookbook instruction](https://psl.noaa.gov/cefi_portal/#cookbooks) on how to access this particular gridded data. You can view the R code reading the raw grid with the grid information on [this paragraph](https://noaa-cefi-portal.github.io/cefi-cookbook/content/data_access/access_opendap/r_get_cefi.html#link-to-data-source-raw-gridded-product). 

>In summary, just like you suspected, you are missing the raw grid "grid info” which is stored at http://psl.noaa.gov/thredds/dodsC/Projects/CEFI/regional_mom6/northwest_atlantic/hist_run/ocean_static.nc 
With both this file and the variable that you are interested in, you should be able to find the proper projection on Lon lat (you should look for geolon and geolat for the btm O2 which is the tracer point coordinates). 

>This is a rather brief explanation. If you have further questions, feel free to reach out to me directly. I also encourage you to explore the cookbook we’ve created, which contains a lot of useful information. However, as the cookbook is still being expanded, there may be some missing elements. If you find anything unclear or have suggestions for improvements, please don’t hesitate to let us know.

**Comment by chiaweh2** [comment]
@btupper It is really nice to see the R related package being develop! I am not expert so I believe I will learned a lot from here. We are currently developing a [python package for utilize and further analyze the CEFI data](https://github.com/NOAA-CEFI-Portal/regional_mom6). Please feel free to check it out. We are hoping to have a similar R package if that is possible. We are starting a co-developement repo soon under the same [GitHub org](https://github.com/NOAA-CEFI-Portal). If you are interested in contributing on the project feel free to drop by!

**Comment by btupper** [comment]
THis is very helpful - I'll check it out.  Thank you!

**Comment by btupper** [comment]
Issue resolved - thanks!  `cefi_var(..., form = 'stars')` now produces a correct curvilinear grid.
